### ISSUE TITLE
Cant confirm accounts

### ISSUE THREAD

**Issue by adamdom** [pennlabs/Penn-Civic-Service#73]
Reason unknown yet. Further research needed

**Comment by adelq** [comment]
Confirmation email is sent successfully, confirmation link matches with intended confirmation code, but actual confirmation page results in:

```
NameError (undefined local variable or method `user' for #<SessionsController:0x007fb5b81e81e0>):
  app/controllers/sessions_controller.rb:27:in `confirm'
```

Further investigation in progress
